---
# handlers file for teaming
#- name: restart networking
#  command: 'ifup {{ template_team }}'
#  ignore_errors: no

- name: restart networking
  service:
    name: network
    state: restarted
  ignore_errors: no
