kind: PersistentVolumeClaim

apiVersion: v1

metadata:

 name: cns-file-claim1

 annotations:

   volume.beta.kubernetes.io/storage-class: glusterfs-storage

spec:

 accessModes:

   - ReadWriteMany

 resources:

   requests:

     storage: 5Gi


