apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: glusterfs-storage-perftrans
  resourceVersion: "709433"
  selfLink: /apis/storage.k8s.io/v1/storageclasses/glusterfs-storage-perftrans
parameters:
  resturl: http://heketi-storage-app-storage.apps.ose-master.example.com
  restuser: admin
  secretName: heketi-storage-admin-secret
  secretNamespace: app-storage
  volumeoptions: performance.stat-prefetch off performance.write-behind off performance.open-behind off performance.quick-read off performance.strict-o-direct on performance.read-ahead off performance.io-cache off performance.readdir-ahead off
provisioner: kubernetes.io/glusterfs
reclaimPolicy: Delete
