apiVersion: v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/image.dockerRepositoryCheck: 2018-07-03T14:44:40Z
  creationTimestamp: null
  generation: 2
  name: httpd
spec:
  lookupPolicy:
    local: false
  strategy:
    sourceStrategy:
      from:
        kind: "ImageStreamTag"
        name: docker-registry.default.svc:5000/httpd:latest
    type: "imagechange"
    imageChange:
      from:
        kind: "ImageStreamTag"
        name: docker-registry.default.svc:5000/httpd:latest
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: docker-registry.default.svc:5000/app-project/httpd:latest
    generation: 2
    importPolicy: {}
    name: latest
    referencePolicy:
      type: Source
status:
  dockerImageRepository: ""
